config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "admin" => "admin#index"

  namespace :courses do
    resources :registrations, only: [ :new, :create ]
  end

  resources :courses do
    resources :course_registrations, only: [ :new, :create ]
  end

  resources :course_registrations, only: [ :index, :show, :edit, :update, :destroy ]

  get "sessions/create"
  get "sessions/destroy"

  get "about", to: "pages#about"
  get "membership", to: "pages#membership"
  resources :courses
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "pages#home"
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[ index show ]
  # load_and_authorize_resource
  before_action :set_course, only: %i[ show edit update destroy ]

  # GET /courses or /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1 or /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses or /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: "Course was successfully created." }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1 or /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: "Course was successfully updated." }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1 or /courses/1.json
  def destroy
    @course.destroy!

    respond_to do |format|
      format.html { redirect_to courses_path, status: :see_other, notice: "Course was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def course_params
      params.require(:course).permit(:name, :image_url, :description, :start_time, :end_time, :capacity, :price)
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_course.html.erb
<div id="<%= dom_id course %>", class="course-card bg-white rounded-lg shadow-md overflow-hidden">
  <%= image_tag(course.image_url, class:"object-cover w-full rounded-t-lg h-96 md:h-auto md:w-48 md:rounded-none md:rounded-s-lg") %>
  <div class="p-4">
    <h3 class="text-lg font-semibold text-gray-800 mb-2"><%= course.name %></h3>
    <p class="text-gray-600 mb-2"><%= course.description %></p>
    <ul class="list-disc pl-4 mb-4">
      <li><strong>Start time:</strong> <%= course.start_time %></li>
      <li><strong>End time:</strong> <%= course.end_time %></li>
      <li><strong>Capacity:</strong> <%= course.capacity %></li>
      <li><strong>Price:</strong> <%= course.price %></li>
    </ul>
  </div>
</div>

app/views/courses/_form.html.erb
<div class="container mx-auto p-4">
  <%= form_with(model: course) do |form| %>
    <% if course.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

        <ul>
          <% course.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="my-5">
      <%= form.label :name, class: "block text-gray-700 text-sm font-bold mb-2" %>
      <%= form.text_field :name, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full"%>
    </div>

    <div class="my-5">
      <%= form.label :image_url, class: "block text-gray-700 text-sm font-bold mb-2" %>
      <%= form.text_field :image_url, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
    </div>

    <div class="my-5">
      <%= form.label :description, class: "block text-gray-700 text-sm font-bold mb-2" %>
      <%= form.text_area :description, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full"  %>
    </div>

    <div class="my-5">
      <%= form.label :start_time, class: "block text-gray-700 text-sm font-bold mb-2" %>
      <%= form.datetime_field :start_time, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full"  %>
    </div>

    <div class="my-5">
      <%= form.label :end_time, class: "block text-gray-700 text-sm font-bold mb-2" %>
      <%= form.datetime_field :end_time, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full"  %>
    </div>

    <div class="my-5">
      <%= form.label :capacity, class: "block text-gray-700 text-sm font-bold mb-2" %>
      <%= form.number_field :capacity, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full"  %>
    </div>

    <div class="my-5">
      <%= form.label :price, class: "block text-gray-700 text-sm font-bold mb-2" %>
      <%= form.text_field :price, class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer"  %>
    </div>

    <%= form.submit "Submit", class: "inline-block rounded bg-indigo-600 px-5 py-3 text-sm font-medium text-white transition hover:bg-indigo-700 focus:outline-none focus:ring" %>
  <% end %>
</div>

app/views/courses/edit.html.erb
<div class="mx-auto wmax-w-screen-xl px-4 py-0 sm:px-6 sm:py-12 lg:px-8 w-full ">
  <div class="flex flex-col items-start gap-4 md:flex-row md:items-center md:justify-between">
    <div>
      <h1 class="text-2xl font-bold text-gray-900 sm:text-3xl">Courses</h1>

      <p class="mt-1.5 text-sm text-gray-500">
        <% content_for :title, "Editing Course" %>
      </p>
    </div>

    <div class="flex items-center gap-4">

      <%= link_to  courses_path, 
        class: "inline-block rounded bg-indigo-600 px-5 py-3 text-sm font-medium text-white transition hover:bg-indigo-700 focus:outline-none focus:ring" do %>
        Back to Courses
      <% end %>
    </div>
  </div>
</div>
<div>

    <%= render "form", course: @course %>

  <span class="inline-flex overflow-hidden rounded-md border bg-white shadow-sm">
    <%= link_to "Show this Course", @course, class:"inline-block px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50 focus:relative" %>
    <%= link_to "Back to courses", courses_path, class:"inline-block px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50 focus:relative" %>
  </span>
</div>

app/views/courses/index.html.erb
<p style="color: green"><%= notice %></p>


<div class="bg-white">
  <div class="mx-auto wmax-w-screen-xl px-4 py-0 sm:px-6 sm:py-12 lg:px-8 w-full ">
    <div class="flex flex-col items-start gap-4 md:flex-row md:items-center md:justify-between">
      <div>
        <h1 class="text-2xl font-bold text-gray-800 sm:text-3xl">Courses</h1>

        <p class="mt-1.5 text-sm text-gray-500">
          <% content_for :title, "Courses" %>
          Please select a course to view more details.
        </p>
      </div>

      <div class="flex items-center gap-4">
      <% if can? :manage, Course %>
        <%= link_to  new_course_path, 
          class: "inline-block rounded bg-indigo-600 px-5 py-3 text-sm font-medium text-white transition hover:bg-indigo-700 focus:outline-none focus:ring" do %>
          New Course
        <% end %>
      <% end %>
      </div>
    </div>
  </div>
</div>
<div id="courses" class="px-4 grid grid-cols-1 gap-1">
  <% @courses.each do |course| %>
    <div class="my-2 bg-red-200 border border-gray-200 rounded-lg shadow ">
      <div class="flex flex-col h-full">
        <div class="flex-1">
          <%= image_tag(course.image_url, class: 'object-cover w-full rounded-t-lg h-96 md:h-96 md:rounded-s-lg') %>
        </div>
        <div class="p-4 flex-1">
          <h2 class="mb-2 text-2xl font-bold tracking-tight text-gray-700"><%= course.name %></h2>
          <p class="mb-2 text-gray-700">
            <%= format_date_range(course.start_time, course.end_time) %>
          </p>
          <p class="mb-4 text-gray-700">
            <%= sanitize(course.description) %>
          </p>
        </div>
        <div class="p-4 flex-1">
          <p class="mb-2 font-bold text-gray-700">
            <%= number_to_currency(course.price) %>
          </p>
          <div class="flex justify-end">
            <%= link_to "More Info", course, class: "p-3 mt-2 border rounded-md text-gray-700 bg-white hover:bg-gray-50" %>
            <!-- <%# <%= link_to "Register", "/courses/#{course.id}/course_registrations/new", class: "p-3 mt-2 border rounded-md text-gray-700" %> -->
          </div>
        </div>
      </div>
    </div>
  <br>
  <% end %>
</div>

app/views/courses/new.html.erb
<% content_for :title, "New course" %>

<div class="container mx-auto p-4 flex flex-col items-center space-y-4">
  <h1 class="text-center align-text-top border-lime-200">Create a New Course</h1>
  <div class="w-full">
    <%= render "form", course: @course %>
  </div>
  <div>
    <%= link_to "Back to courses", courses_path %>
  </div>
</div>

app/views/courses/show.html.erb
<p style="color:green"><%= notice %></p>

<%= render @course %>

<span class="inline-flex overflow-hidden rounded-md border bg-white shadow-sm">
  <%= link_to "Back to courses", courses_path, class:"inline-block px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50 focus:relative" %>
  <%= link_to "Register", "/courses/#{@course.id}/course_registrations/new", class: "inline-block px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50 focus:relative" %>
  <% if can? :manage, @course %>
    <%= link_to "Edit this course", edit_course_path(@course), class:"inline-block px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50 focus:relative" %>
    <%= button_to "Destroy", @course, method: :delete, class:"inline-block px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50 focus:relative" %>
  <% end %>
</span>

<p class="text-green-500"><%= notice %></p>