config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "admin" => "admin#index"

  namespace :courses do
    resources :registrations, only: [ :new, :create ]
  end

  resources :courses do
    resources :course_registrations, only: [ :new, :create ]
  end

  resources :course_registrations, only: [ :index, :show, :edit, :update, :destroy ]

  get "sessions/create"
  get "sessions/destroy"

  get "about", to: "pages#about"
  get "membership", to: "pages#membership"
  resources :courses
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "pages#home"
end

app/models/course_registration.rb
class CourseRegistration < ApplicationRecord
  PAYMENT_OPTIONS = [ "Debit Card", "Credit Card" ]

  belongs_to :course
  has_many :users

  validates :email, presence: true
  validates :pay_type, presence: true, inclusion: { in: PAYMENT_OPTIONS }
  validates :user_id, presence: true
  validates :course_id, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :age, presence: true
  validates :member, presence: true
end

app/controllers/course_registrations_controller.rb
class CourseRegistrationsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[new create]
  before_action :set_course_registration, only: %i[show edit update destroy]
  before_action :set_course, only: %i[new create]

  # GET /registrations or /registrations.json
  def index
    @course_registrations = CourseRegistration.all
  end

  # GET /registrations/1 or /registrations/1.json
  def show
  end

  # GET /course_registrations/new
  def new
    @course = Course.find(params[:course_id])
    @course_registration = @course.course_registrations.build
  end

  # GET /registrations/1/edit
  def edit
  end

  # POST /course_registrations
  def create
    @course_registration = CourseRegistration.new(course_registration_params)
    @course_registration.course = @course
    @course_registration.user = current_user

    respond_to do |format|
      if @course_registration.save
        format.html { redirect_to @course_registration, notice: "Registration was successfully created." }
        format.json { render :show, status: :created, location: @course_registration }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @course_registration.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /registrations/1 or /registrations/1.json
  def update
    respond_to do |format|
      if @course_registration.update(course_registration_params)
        format.html { redirect_to @course_registration, notice: "Course registration was successfully updated." }
        format.json { render :show, status: :ok, location: @course_registration }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @course_registration.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /registrations/1 or /registrations/1.json
  def destroy
    @course_registration.destroy!

    respond_to do |format|
      format.html { redirect_to course_registrations_path, status: :see_other, notice: "Registration was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course_registration
      @course_registration = CourseRegistration.find(params[:id])
    end

    def set_course
      @course = Course.find(params[:course_id])
    end

    # Only allow a list of trusted parameters through.
    def course_registration_params
      params.require(:course_registration).permit(:course_id, :user_id)
    end
end

app/views/course_registrations/_course_registration.html.erb
<div id="<%= dom_id course_registration %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Email:</strong>
    <%= course_registration.email %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">First Name:</strong>
    <%= course_registration.first_name %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1">Last Name:</strong>
    <%= course_registration.last_name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Pay type:</strong>
    <%= course_registration.pay_type %>
  </p>

</div>

app/views/course_registrations/_form.html.erb
<%= form_with(model: @course_registration, class: "contents") do |form| %>
  <% if @course_registration.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(@course_registration.errors.count, "error") %> prohibited this course registration from being saved:</h2>

      <ul>
        <% @course_registration.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="my-5">
    <%= form.label :email %>
    <%= form.email_field :email, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :pay_type %>
    <%= form.select :pay_type, CourseRegistration::PAYMENT_OPTIONS, { prompt: 'Select a payment method'}, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit "Submit", class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/course_registrations/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing registration</h1>

  <%= render "form", registration: @registration %>

  <%= link_to "Show this registration", @registration, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to Courses", courses_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/course_registrations/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Registrations" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Registrations</h1>
    <%= link_to "New registration", new_registration_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="registrations" class="min-w-full">
    <% @registrations.each do |registration| %>
      <%= render registration %>
      <p>
        <%= link_to "Show this registration", registration, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      </p>
    <% end %>
  </div>
</div>

app/views/course_registrations/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New registration</h1>

  <%= render "form", registration: @course_registration %>

  <%= link_to "Back to Courses", courses_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/course_registrations/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @registration %>

    <%= link_to "Edit this registration", edit_registration_path(@registration), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to courses", courses_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this registration", @registration, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>