config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "admin" => "admin#index"

  namespace :courses do
    resources :registrations, only: [ :new, :create ]
  end

  resources :courses do
    resources :course_registrations, only: [ :new, :create ]
  end

  resources :course_registrations, only: [ :index, :show, :edit, :update, :destroy ]

  get "sessions/create"
  get "sessions/destroy"

  get "about", to: "pages#about"
  get "membership", to: "pages#membership"
  resources :courses
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "pages#home"
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    can :read, Course

    return unless user.present?

    can :manage, CourseRegistration, user: user

    return unless user.admin?

    can :manage, :all
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/course.rb
class Course < ApplicationRecord
  validates :name, :description, :image_url, :start_time, :end_time, :capacity, presence: true
  validates :name, uniqueness: true
  validates :image_url, allow_blank: true, format: { with: %r{\.(jpg|png)\z}i, message: "must be a URL for JPG or PNG image." }
  validates :price, numericality: { greater_than_or_equal_to: 0.01 }

  has_many :course_registrations
end

app/models/course_registration.rb
class CourseRegistration < ApplicationRecord
  PAYMENT_OPTIONS = [ "Debit Card", "Credit Card" ]

  belongs_to :course
  has_many :users

  validates :email, presence: true
  validates :pay_type, presence: true, inclusion: { in: PAYMENT_OPTIONS }
  validates :user_id, presence: true
  validates :course_id, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :age, presence: true
  validates :member, presence: true
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/member.rb
class Member < ApplicationRecord
end

app/models/registration.rb
class Registration < ApplicationRecord
  enum pay_type: {
    "Cash" => 0,
    "Credit Card" => 1
  }
  belongs_to :course
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable


  def member?
    self.present?
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
    @total_members = Member.count
    @total_courses = Course.count
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[ home about membership ]
  def home
  end

  def about
  end

  def membership
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_url, notice: "User #{@user.first_name @user.last_name} was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_url, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy!

    respond_to do |format|
      format.html { redirect_to users_path, status: :see_other, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:email, :first_name, :password, :password_confirmation)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    def format_date_range(start_time, end_time)
      if start_time.to_date == end_time.to_date
        "#{start_time.strftime('%A, %B %d, %Y')}"
      else
        "#{start_time.strftime('%A, %B %d, %Y')} - #{end_time.strftime('%A, %B %d, %Y')}"
      end
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<div class="w-full">
  <h1 class="mx-auto text-lg font-bold text-4xl">Welcome</h1>
  <p>
    It's <%= Time.now %>.
    We have <%= pluralize(@total_members, "member") %>.
    We have <%= pluralize(@total_courses, "course") %>.
  </p>
</div>

app/views/layouts/_navbar.html.erb
<nav class="relative flex items-center justify-between sm:h-10 md:justify-center py-6 px-4 mt-7">
    <div class="flex items-center flex-1 md:absolute md:inset-y-0 md:left-0">
        <div class="flex items-center justify-between w-full md:w-auto">
            <a href="" aria-label="Home">
                <img src="<%= asset_path 'LVYC_Logo.svg' %>" height="40" width="40" />
            </a>
            <div class="-mr-2 flex items-center md:hidden">
                <button type="button" id="main-menu" aria-label="Main menu" aria-haspopup="true" class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:bg-gray-100 focus:text-gray-500 transition duration-150 ease-in-out">
                    <svg stroke="currentColor" fill="none" viewBox="0 0 24 24" class="h-6 w-6"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"></path></svg>
                </button>
            </div>
        </div>
    </div>
    <div class="hidden md:flex md:space-x-10">
        <%= link_to "Home", root_path, class: "font-medium text-gray-500 hover:text-gray-900 transition duration-150 ease-in-out" %>
        <%= link_to "Courses", courses_path, class: "font-medium text-gray-500 hover:text-gray-900 transition duration-150 ease-in-out" %>
        <%= link_to "Membership", membership_path, class: "font-medium text-gray-500 hover:text-gray-900 transition duration-150 ease-in-out" %>
        <%= link_to "About Us", about_path, class: "font-medium text-gray-500 hover:text-gray-900 transition duration-150 ease-in-out" %>
    </div>
    <div class="hidden md:absolute md:flex md:items-center md:justify-end md:inset-y-0 md:right-0">
        <span class="inline-flex">
            <% if !user_signed_in? %>
                <%= link_to "Login", new_user_session_path, class: "mx-2 inline-flex items-center px-4 py-2 border border-transparent text-base leading-6 font-medium text-blue-600 hover:text-blue-500 focus:outline-none transition duration-150 ease-in-out" %>
            <% else %>
                <%= link_to "Logout", destroy_user_session_path, method: :delete, data: { turbo_method: :delete }, class: "mx-2 inline-flex items-center px-4 py-2 border border-transparent text-base leading-6 font-medium text-blue-600 hover:text-blue-500 focus:outline-none transition duration-150 ease-in-out" %>
            <% end %>
        </span>
        <span class="inline-flex rounded-md shadow ml-2">
            <% if !user_signed_in? %>
                <%= link_to "Sign Up", new_user_registration_path, class: "inline-flex items-center px-4 py-2 border border-transparent text-base leading-6 font-medium rounded-md text-white bg-blue-600 hover:bg-blue-500 focus:outline-none focus:border-blue-700 transition duration-150 ease-in-out" %>
            <% end %>
        </span>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title><%= content_for(:title)%></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", media: 'all', "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body class="bg-white text-grey-800 font-montserrat">
    <%= render "layouts/navbar" %>

    <main>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

      <%= yield %>
    </main>
  </body>
</html>

app/views/membership/_membership_form.html.erb
<p>Hi, <%= current_user.first_name %>!</p>
<br>
<p>You are <strong>not</strong> yet a member, but if you'd like to submit an application please fill out the following form:</p>
<!-- 
Implement mailer creation for membership application.
-->

app/views/membership/_membership_info.html.erb
<p>Welcome, <em><%= current_user.first_name %></em>!</p>
<br>
<p>Here are your membership details:</p>

app/views/pages/about.html.erb
<!--
<div class="p-4">
    <h1 class="text-gray-800 text-4xl font-bold text-left mt-10">About Us</h2>
    <p class="text-gray-700 text-lg text-left mt-5">We are a dedicated team committed to providing exceptional [service or product]. Our mission is to [mission statement].</p>

    <hr class="my-10 border-gray-300">

    <h3 class="text-gray-800 text-2xl font-bold text-left">Our Values</h3>
    <ul class="text-gray-800 text-lg list-disc mt-5">
        <li class="pl-4">Value 1</li>
        <li>Value 2</li>
        <li>Value 3</li>
    </ul>

    <hr class="my-10 border-gray-300">

    <h3 class="text-gray-800 text-2xl font-bold text-left">Our Team</h3>
    <p class="text-gray-800 text-lg text-left mt-5">Meet our talented team members.</p>
    <hr class="my-10 border-gray-300">

    <h3 class="text-gray-800 text-2xl font-bold text-left">Contact Us</h3>
    <p class="text-gray-800 text-lg text-left mt-5">Get in touch with us today.</p>
</div>
-->
<div class="p-4">
    <h1 class="text-gray-800 text-4xl font-bold text-left my-10">About Us</h1>

    <div class="col-10 content">
        <%= image_tag 'about_us.jpg', class: 'border border-solid border-rounded border-gray-300 float-right h-20 w-72 m-5 md:h-max-30' %>

        <h3 class="text-gray-800 text-2xl font-bold text-left my-5">Learn to Sail</h3>
        <p>Discover the charm of our club and the stunning waters we call home. Whether you're a seasoned sailor or a newcomer to the sport, you'll find everything you need to get started on our <%= link_to "courses page", courses_path, class: "text-blue-600 hover:underline" %>.</p>
        <h3 class="text-gray-800 text-2xl font-bold text-left my-5">Join our Community</h3>
        <p>The Lake Vernon Yacht Club is a not-for-profit community of sailors and friends nestled on the shores of beautiful Lake Vernon in Huntsville. Our clubhouse offers stunning views of the lake and surrounding nature, providing the perfect setting for relaxation and recreation. We invite you to explore our club's history and traditions, and to become a part of our vibrant community. To get started, create a free account to view events, participate in courses and meet fellow sailors.</p>
    </div>

    <hr class="my-10 border-gray-300">

    <h3 class="text-gray-800 text-2xl font-bold text-left">Contact Us</h3>
    <p class="text-gray-800 text-lg text-left my-5">Get in touch with us today.</p>
        <p><strong>Phone:</strong> <a href="tel:###-###-####" class="text-blue-600 hover:underline">123-456-7891</a></p>
        <p><strong>Email:</strong> <a href="mailto:office@example.ca" class="text-blue-600 hover:underline">office@example.ca</a></p>
</div>

app/views/pages/home.html.erb
<div class="p-4">
    <h1 class="text-gray-800 font-bodoni font-bold text-3xl">Lake Vernon Yacht Club</h1>
    <hr class="my-10 border-gray-300">

    <h3 class="text-gray-800 font-montserrat font-bold text-2xl ">History</h3>
    <p class="text-gray-800 font-montserrat text-lg mt-5">
        Since its founding in 2024, the Lake Vernon Yacht Club has been a cornerstone of the community, offering a haven for boating enthusiasts and a vibrant social hub. Nestled on the serene shores of Lake Vernon, our Club provides a picturesque setting for relaxation, recreation, and competitive sailing. Our members enjoy a range of amenities, including state-of-the-art boating facilities, a clubhouse with stunning lake views, and a variety of social events throughout the year. From casual gatherings to formal dinners, our Club offers something for everyone. At the heart of our Club is a shared passion for sailing. We host a variety of sailing events, from casual races to competitive regattas, catering to sailors of all skill levels. Whether you're a seasoned sailor or a newcomer to the sport, you'll find a welcoming and supportive community at the Lake Vernon Yacht Club.
    </p>

    <hr class="my-10 border-gray-300">

</div>

app/views/pages/membership.html.erb
<div class="container-fluid m-0 p-0">
    <div class="row m-0 p-0">
        <div class="col-12 m-0 p-0">
            <%= image_tag('membership_banner.jpg', class: "w-full h-96 object-cover object-bottom") %>
        </div>
    </div>
    <div class="row m-0 p-2">
        <div class="col-1">&nbsp;</div>
        <div class="col-10">
            <h1 class="text-gray-800 text-4xl font-bold font-montserrat py-4 px-6 mx-2">Membership</h1>
            <hr class="border-t-2 border-gray-300 my-4">
        </div>
        <div class="col-1">&nbsp;</div>
    </div>
</div>
<div class="container mx-auto p-3">
    <% if current_user %>
        <% if current_user.member? %>
            <%= render 'membership/membership_info' %>
        <% else %>
            <%= render 'membership/membership_form' %>
        <% end %>
    <% else %>
        <p>Please log in or sign-up to manage your membership.</p>
    <% end %>
</div>